name: backup

on:
  schedule:
    - cron: "0 0 * * *" #at the end of every day
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  download-backup:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - run: mkdir backups
      - run: "curl https://uservoice.bcc.no/api/v1/export/backup --output backups/backup-${{ steps.date.outputs.date }}.zip --header 'authorization: Bearer ${{ secrets.API_Key }}'"
      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Copy files to the bucket with the AWS CLI
        run: |
          aws s3 cp backups/* s3://uservoice-backups
