name: backup

on:
  schedule:
    - cron: "0 0 * * *" #at the end of every day
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: uservoice

jobs:
  download-backup:
    runs-on: ubuntu-latest
    environment: Integration
    steps:
      - run: "curl https://int-uservoice.bcc.no/api/v1/export/backup --output backup-${{ steps.date.outputs.date }}.zip --header 'authorization: Bearer ${{ secrets.API_Key }}'"
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/**.zip
          name: backup-${{ steps.date.outputs.date }}
        if: (${{ job.status }} != 'cancelled')
